### ISSUE TITLE
size_type should be size_t

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/fixed_capacity_vector#30]
`size_type` should be `size_t`, the type used to storage the vector size is the one that should be "as small as possible".

**Comment by viboes** [comment]
When will be move to a signed type for `size_type`?

**Comment by gnzlbg** [comment]
The STL2 does this for ranges, but nobody has suggesting modernizing the
containers for the STL2 yet...

**Comment by viboes** [comment]
Agreed. We will need a paper that changes this for std2.

**Comment by CaseyCarter** [comment]
> the type used to storage the vector size is the one that should be "as small as possible".

...which can be left to QoI.

**Comment by gnzlbg** [comment]
So this is fixed. @CaseyCarter should that QoI issue be mentioned somewhere? (currently it is not).

**Comment by CaseyCarter** [comment]
> should that QoI issue be mentioned somewhere? (currently it is not)

I wouldn't bother.
